CARD_NEW = 0
CARD_LRN = 1
CARD_DUE = 2
CARD_FILTERED = 3

# Queue types
QUEUE_SCHED_BURIED = -3
QUEUE_USER_BURIED = -2
QUEUE_SUSPENDED = -1
QUEUE_NEW_CRAM = 0
QUEUE_LRN = 1
QUEUE_REV = 2
QUEUE_DAY_LRN = 3
QUEUE_PREVIEW = 4
